/*
 * Copyright 2022 Compose Academy
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package academy.compose.blog

import academy.compose.blog.model.Post

object PostFactory {

    fun makePosts(): List<Post> {
        return listOf(
            Post(
                "1",
                "Beyond Android",
                "hitherejoe",
                "http://picsum.photos/800/400",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\n\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.",
                "27/03/2022",
            ),
            Post(
                "2",
                "The Constraint Layout",
                "hitherejoe",
                "http://picsum.photos/800/600",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\n\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\n" +
                    "\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.",
                "27/03/2022",
            ),
            Post(
                "3",
                "The end of XML",
                "hitherejoe",
                "http://picsum.photos/900/400",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\n\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\n" +
                    "\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.",
                "27/03/2022",
            ),
            Post(
                "4",
                "Diving into Jetpack Compose",
                "hitherejoe",
                "http://picsum.photos/600/400",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\n\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\n" +
                    "\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.",
                "27/03/2022",
            ),
            Post(
                "5",
                "Compose + KMP",
                "hitherejoe",
                "http://picsum.photos/500/500",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\n\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\n" +
                    "\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.",
                "27/03/2022",
            ),
            Post(
                "6",
                "Tackling Android Performance",
                "hitherejoe",
                "http://picsum.photos/700/600",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\n\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\n" +
                    "\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.",
                "27/03/2022",
            ),
            Post(
                "7",
                "Accessibility Patterns",
                "hitherejoe",
                "http://picsum.photos/800/700",
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\n\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.\n" +
                    "\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sed ante at nisi tincidunt ornare. Quisque lobortis lacus ipsum, a semper ipsum molestie ac. Vestibulum ullamcorper, elit a molestie gravida, purus felis dignissim turpis, non feugiat metus lacus a augue. Duis consequat tincidunt justo vel sagittis. Fusce aliquam ut mi a scelerisque. Nam vulputate augue justo, id dictum urna ornare eu. Aenean quis bibendum nisl, non mollis mauris. Nullam dui enim, feugiat nec sollicitudin eget, cursus vel risus. Pellentesque vel quam cursus, sodales lectus sit amet, molestie ipsum. Curabitur eleifend auctor egestas. Etiam gravida magna ut condimentum vulputate. Fusce ac libero nec arcu condimentum dictum. Donec at neque molestie, lacinia elit quis, ultricies turpis.",
                "27/03/2022",
            )
        )
    }
}